import pandas as pd
import os

# =============================================================================
# CONFIGURATION & FILE PATHS
# =============================================================================

# 1. Prediction File: Contains the text predicted by the ASR model.
#    Structure: file_name; prediction; source_file
PRED_CSV = "3_results/metadata_inference_ordered.csv"

# 2. VAD File: Contains the timestamps (start/end) for each segment.
#    This file was generated by the cutting script (2_cut_raw_audio.py).
#    Structure: file_name, start, end, duration, transcription
VAD_CSV = "1_data_prepared/inference_segments/metadata_inference.csv"

# 3. Output Directory: Where the final "Global" TextGrids will be saved.
OUTPUT_DIR = "3_results/global_textgrids/"
os.makedirs(OUTPUT_DIR, exist_ok=True) # Create folder if it doesn't exist

print("--- Starting TextGrid Generation Process ---")

# =============================================================================
# DATA LOADING & MERGING
# =============================================================================

print(f"Loading predictions from: {PRED_CSV}")
# Note: PRED_CSV uses a semicolon (;) separator
df_pred = pd.read_csv(PRED_CSV, sep=';')

print(f"Loading timestamps from: {VAD_CSV}")
# Note: VAD_CSV uses a comma (,) separator (standard CSV)
df_vad = pd.read_csv(VAD_CSV, sep=',')

# CRITICAL STEP: Merging the two dataframes.
# We join them on the 'file_name' column (e.g., 'mon_Coo...seg001.wav').
# This attaches the 'start' and 'end' times from VAD_CSV to the 'prediction' text in PRED_CSV.
print("Merging text predictions with timestamps...")
df_merged = pd.merge(df_pred, df_vad, on='file_name', how='inner')

print(f"Merge successful: {len(df_merged)} segments ready for processing.")

# =============================================================================
# TEXTGRID GENERATION LOOP
# =============================================================================

# We group the data by 'source_file' to reconstruct the original long recordings.
# Example: All segments belonging to 'mon_Coo_24_04_2017' are processed together.
for source_file, group in df_merged.groupby('source_file'):
    
    # 1. Sort segments chronologically by start time to ensure correct order
    group = group.sort_values('start')
    
    # 2. Determine the total duration of the TextGrid
    # We take the end time of the very last segment as the total length
    global_xmax = group['end'].max()
    
    # 3. Construct the TextGrid Header (Praat format)
    # This block defines the file type and the main IntervalTier
    header = f"""File type = "ooTextFile"
Object class = "TextGrid"

xmin = 0 
xmax = {global_xmax} 
tiers? <exists> 
size = 1 
item []: 
    item [1]:
        class = "IntervalTier" 
        name = "transcription_auto" 
        xmin = 0 
        xmax = {global_xmax} 
        intervals: size = {len(group)} 
"""
    
    # 4. Construct the Intervals (The actual data)
    intervals_content = ""
    
    # Iterate through each segment in the current group
    for i, (_, row) in enumerate(group.iterrows(), 1):
        # Extract timing
        xmin = row['start'] 
        xmax = row['end']
        
        # Extract and sanitize text
        text = str(row['prediction'])
        
        # Handle empty or NaN values (replace with empty string)
        if text == "nan" or text == "<>":
            text = ""
            
        # IMPORTANT: Replace double quotes (") with single quotes (') 
        # because double quotes break the TextGrid file structure.
        text = text.replace('"', "'") 
        
        # Append this interval to the content string
        intervals_content += f"""        intervals [{i}]:
            xmin = {xmin} 
            xmax = {xmax} 
            text = "{text}" 
"""

    # 5. Write the final file
    out_path = os.path.join(OUTPUT_DIR, f"{source_file}.TextGrid")
    
    try:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(header + intervals_content)
    except Exception as e:
        print(f"Error writing {source_file}: {e}")

print(f"SUCCESS: All Global TextGrids have been saved in '{OUTPUT_DIR}'")